### PR TITLE
Add CLA accepted flag to database

### PR DESCRIPTION
**Pull request by jt-nti**
Signed-off-by: James Taylor <jt-git@nti.me.uk>

### CODE REVIEW

**Comment by jt-nti** [comment]
Does this look like a reasonable first step for #72?

**Comment by Floppy** [comment]
Yep, makes sense to me!

**Comment by jt-nti** [comment]
Any idea why the checks aren't running?

**Comment by Floppy** [comment]
No, must be a fork thing? It looks fine so I'll merge.

**Comment by Floppy** [comment]
Hopefully it will all be fine on master 🤠

**Comment by jt-nti** [comment]
What's the worst that could happen?! Will the db get migrated? 😬
Now I just need to figure out how to make use of it without breaking all the things... I was wondering about attempting to putt a link to the cla with an "I agree" checkbox in https://github.com/openpolitics/groupthink/blob/master/app/views/edit/message.html.erb

**Pull request merged**
